spring:
  thymeleaf:
    prefix: classpath:/templates/

  data:
    mongodb:
      uri: mongodb://admin:123@127.0.0.1:27017
      database: test
  output:
    ansi:
      enabled: always

  mail:
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.gmail.com
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          starttls:
            enable: true
          auth: true
        host: smtp.gmail.com
        username: arilsonsantos@gmail.com
        password: Ironmaiden@123



security:
  oauth2:
    client:
      scope:
      - password
      client-id: clientId
      client-secret: "{bcrypt}$2a$10$42B0dm6qcfpojx7bbIjGYOjNJbEzc.MeWozTkhCHRKyKXKXUvxmwm"

jwt:
  secret: secret
  validation:
    token: 60

default:
  sender: arilsonsantos@gmail.com
  recipient: arilsonsantos@gmail.com
  url: http://localhost:8080


