
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  thymeleaf:
    prefix: classpath:/templates/
  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017/?minPoolSize=10
      connect-timeout: 1000
      socket-keep-alive: true
      database: test
  output:
    ansi:
      enabled: always
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 9f46419e235e89
    password: 3f26d992bacb93
    protocol: smtp
    properties:
      mail:
        smtp:
          - auth: true
          - starttls:
              enable: true

security:
  oauth2:
    client:
      scope:
      - password
      client-id: clientId
      client-secret: "{bcrypt}$2a$10$y0vUfW7GsTTjbk..7pBqdOs0ikeF16DcIsuWbMLzG08Y/2fr75bIi"

jwt:
  secret: secret
  validation:
    token: 60

default:
  sender: orion@api.com
  url: http://localhost:8080

#server:
#  servlet:
#    context-path: /registry
