spring:

  thymeleaf:
    prefix: classpath:/templates/

  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017/?minPoolSize=10
      connect-timeout: 1000
      socket-keep-alive: true
      database: test
  output:
    ansi:
      enabled: always
#  mail:
#    host: smtp.mailtrap.io
#    port: 2525
#    username: 4f967c13da91c3
#    password: 762a7eb99def56
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

security:
  oauth2:
    client:
      scope:
      - password
      client-id: clientId
      client-secret: "{bcrypt}$2a$10$y0vUfW7GsTTjbk..7pBqdOs0ikeF16DcIsuWbMLzG08Y/2fr75bIi"

jwt:
  secret: secret
  validation:
    token: 60

default:
  sender: orion.aws@outlook.com
  recipient: orion.aws@outlook.com
  url: http://localhost:8080


